### ISSUE TITLE
`req_url_query()` makes request fail on Docker Compose

### ISSUE THREAD

**Issue by ErdaradunGaztea** [r-lib/httr2#228]
Now, I don't have much idea on how to make a short reproducible example for this one, but I wanted to note this problem and perhaps get some tips on where else to post it.

### Context
I'm developing an app that consists of (among others) a plumber API. Other modules use it through httr2. Each module is dockerized in a separate service with Docker Compose. I use service names to define URLs for requests (a typical request would be something like `api:5050/entities/188`).

Some components of `compose.yaml` file:

```
version: "3.9"
services:
  api:
    networks: 
      - somenetwork
  othermodule:
    depends_on: 
      - api
    networks: 
      - somenetwork
    environment:
      - API_IP=api

networks:
  - somenetwork
```

### Problem
In most cases the requests work just fine. I've narrowed down the problem to `req_url_query()` -- if I don't add URL parameters to the query, my `GET` requests work alright. If I add parameters using `req_body_json()`, this is fine too (and that's what I used to circumvent my issue).

However, after adding `req_url_query()` parameters I get the following error:

`Protocol "api" not supported or disabled in libcurl`

(`api` being the name of the service)
